{% set name = "autobahn" %}
{% set version = "22.3.2" %}
{% set sha256 = "58a887c7a196bb08d8b6624cb3695f493a9e5c9f00fd350d8d6f829b47ff9036" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - txaio >=21.2.1
    - cryptography >=3.4.6
    - hyperlink >=21.0.0

test:
  imports:
    - autobahn
    - autobahn.rawsocket
    - autobahn.wamp
    - autobahn.websocket
    - autobahn.util

about:
  home: https://github.com/crossbario/autobahn-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket and WAMP in Python for Twisted and asyncio

  doc_url: https://autobahn-python.readthedocs.io
  dev_url: https://github.com/crossbario/autobahn-python

extra:
  recipe-maintainers:
    - synapticarbors
