{% set name = "autobahn" %}
{% set version = "20.12.3" %}
{% set sha256 = "410a93e0e29882c8b5d5ab05d220b07609b886ef5f23c0b8d39153254ffd6895" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - txaio >=20.4.1
    - cryptography >=2.9.2
    - hyperlink >=20.0.1

test:
  imports:
    - autobahn
    - autobahn.rawsocket
    - autobahn.wamp
    - autobahn.websocket
    - autobahn.util

about:
  home: https://github.com/crossbario/autobahn-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket and WAMP in Python for Twisted and asyncio

  doc_url: https://autobahn-python.readthedocs.io
  dev_url: https://github.com/crossbario/autobahn-python

extra:
  recipe-maintainers:
    - synapticarbors
