travis:
  secure:
    BINSTAR_TOKEN: EMv34e8skVSoIa+6YXncbpFnQT4CSgC4MDjM/E9Ov5RKXldj/Wt55XLE3RBz7fIPpEc8P/VQQYY8YlWYA6fBZbSJMc4cYqyBF6NwmGVk2ho5b/Y/HMLKr5H34MMqqCwmr1XHQif3L0ZznxyME5HzLhpXYpyH2hb7tcmxXJApNGUyRI/e7Ut5ABBoB0EBbkQlxUfWl6IRgvY4+UK36BipJYtygd7wJb6DNmmFn4p85J9r5kPpEuAd730pjCN4Bc6+aaapj+XbYK5cFuiJHfZmNLdRYGHFYOqIWmdgFOWVMRRHauBJeV7Af1ttwiW8N4Y6olvJVNNDGiBCHJF7X0qvz4jKZOOtYeD3wM5qc0gATRIxJgPA0snSNFY4ijnQ14K65ms/nUgh8ZeG7GAlIFPzBz8wiVcU29NHIFn4v8WzOmxaRvofWM+DzxxbDWj4JW6p0KYkffrQ7InNaP1dMlc5mAmyzSWe8SGriOEWgROiCYYVAkXK+7VA/rr/ePwRYc10/Y+5aBzcLV2vo/pv7O31nh/cKs3OkodDdinycflarYRzZk2vqNX8OEilfiA6zbhtZQAkMGLpU6O+o8qmO0cKwKpdg1qW3HlbDX04ysj6mbqKawrDdSzjisl0ft4bCgvHjtGypLF2oGMyp6DcSjUb0Jk+V6+MwhSSsarreG6RZ7A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
