travis:
  secure:
    BINSTAR_TOKEN: MmO2rxyVuBcOYRVCPl0eZ6r3dWxfXErgirFW9BWnMn8gb98KywBX6vQ20NEZ7V65MRyNj/9Mue6XeaksEUBuSEX06GZiAmyQjpR8tlykMVmiyBm2LsJ7SWDAMNSMAq1X/Ws4lluAviGYMKOr4V/uOcvst+fsHRs627N7OJhu532T55bjmM9m3LayYrISQu1Exd8YCHBWXBqeEaM5nckKkD8dL+BJUiyL7pfEG9rSzyQjlGfLJWHjrlT+5NbsAO414U3iStYzw1yZ+J/7zShcJaCZsb22Te86bSrdKGlvHAkWKn4o/ogiTeny+aYQe+L9ZbY4+0MBT/N7E079EGtfRm11NKPvyl3XlvzweDBZGeAHqXSs9gm1mkXZYPcgwlIjzx6zBG3KiKewFfN5Ka9fJDHnUOc9G/iWTbxyp4gigOq48cAv54bPrI2P+aAcK+3EMyhC1VxTMisO88VbJXhd9QUMePpdT37jjGChzWhNBNxAD5b8BP4XU+I7cQEnnSOTbUjxxL3JRjFpyKXofpkc0nn+wfyze4L/Ot3Vewx4qgfoRTo8NwcKgUVwMhFXrfy5Nyt3g7jdonyNP95dn+2MZFhBxBlOoX/Qst1UvHB3Ij+5CCPSS5/tLLBqlsHlW5GIB2jXsFeCMwq1qcXtzdw7mfUHTmMD+H4WqmXgFkkYPwA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
