travis:
  secure:
    BINSTAR_TOKEN: o9Nuvc5RoM6al0waNyGdD8jruoeDgAYpNpHy9kqqsCyue28wwLqYtmPgq9P+XHa+CAIt6bk9zRF4F7Tln5NjOjGVwBx/akXS4G46Zz0zGYNNs3yi4rxvXo5d12GVhkocDIxlxwceuevdm679htXxQUu2pd5JpdryW+gEuz05v/BmgaQMVWrE9PIDp5by0JsY8r+NszUS5hu8Z8R0z+Y9J+J3YCgwTBJY9ygPwuPDPPHYq+rbvJyJzy6wG7MNWaP9O0o0EBCeCQzSpi4xHDQeAJIOYV+QHjs50XZ4T18ER0FOjlevDS+Jfug1jxHj388CXMglPpGSArzbhrvmiYV/XA9I8sVXcBqz7JLRXEOWwx/c1nqn3wn6KsdhEwtACzkGnSFhTOYyDeZoZ9iHoblhMixiMtZS1LjSgviCkUFx0OgtRUmhQ87Q+uTFuSRsh8lS1l6M3aVaN/uUxKPvFxp6lQ9GmE8iE0zO9mxsofM0gm5fSrCe6FrWEYh7rTHrTSuVscr7GqWKlN8FTC+O+vWJuyLji1l2+pe6bMr8DKK01hjlc4VrYleKPLPZhAxjYNzaM01aeTKyRDzILgO0S+aaOuRNxyJ1Xe7slG/CjnP8dJvH63MQuzeeSB5SulM2FkabK3lQsVZ2RQ1QOtXlpaGps2wAtHT1Mv5d52v8MGX4bLM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
