travis:
  secure:
    BINSTAR_TOKEN: dVO6CMFL+lF8yitHDvuoWvEgeelW0eyw8/hqaSSRLvtbyHACWosP7skxs1VaImNTZD3QBN/Z2BARn/qt3JSuo0h4XQpM5PIUNSvL4zJ0Bah6xS6GdHpKuINFmFKzVh6sOiO32DnC0hY3UWnITUE/BsmplYFKNkf3J2UOi4LaQbr7H6Gdfcb0P83P7gkZIadE9cb7LxnkSHTWpkKjGY7ahCm/1WIZpsab4IzjPtUaj9g9RvCImeAuTOTr/+OTLLBAuBt7211xfkFsY2zwyr+BTl1dAzrYIPN3M7B3g5I6PSeAmnrFpBPlJnJ3+6cfJC1OLwxMYghwFHM+ljhJvz9/F/E44dldq4dKc29stddjfEXcQO5Njnxv3Nzs0jKrJimqdoRcM/rwKko0+lABOZ25dVMCrPcRIM6jVJBPwHJfdlbBfS8ePY9pSf6CnTeT0nkLTl1xCnsa1rvmt2QOF5ukGmUUR002SXIq8h63WrjYmRwUy7/15HiSWmxytv0qflIDt+y1UHg8b7X8uU2d3+XP/AhzvKBw+MEUpl3MxxcviLx35D/LXem9C5GOItVIwLLERZf1ciqkKsa0DEwVkeLN97hhlFZUo9HgyeuYRHXFfkyT8P3k/6Swy1m/GDqSCXjyfZt87jpQ75RUZmcRe2Iru2qi8soVgD44REQlEZq5pyg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
