travis:
  secure:
    BINSTAR_TOKEN: Ponc6/rQECdN7J027S0WoCm7uci4CvBdi/vcgET+pmX3WjsVvwimw6RN7b1Au9DQReCi0dN3tRlO7yaOltih1RiPSAp6JC+XrMTY9o7k9mnlqOuEt3nQEes76N9F4Oe/6znJ+YYw8AaB6uf+KKWP/QqNt+B4stqsgY7HD2O9UIY5aaO+jDwDWqlHkyMb0IghdcekGv1e8iGLtgmfVx5/VF+KVh9AZ3SXewEMt3LVXn8Sz5VG0VBkTwzprdPpfw8iZAZ+rAB71tu9hlxtuLbXrJPQl+T1SYnYyqiXXDeEVmiVVG36taGyJECozQCniHBDD+/rBNjVIKBoWBPuethLuGuznn6bxJlRMx6DPAikNJTvOjYdGYFnygpbC9hBO7vT+Y/POT0AvCAjhKpzAtpsXdRrwIDvTb8HlyCYoTGpazhgr/MVbYPI4tiONiw3Yeyl0Frxhzpw1eEVz7DXD10meIq9Un4ZppVSKS6i8p3fihtzk+ilsk2v6af1VybkJmMuzq5v+HA3j80MMr9+lz4i36aKVMlG3hSph5e4HIhF09BJdCFpqj2ctaq3mSUf7mRoMwgT5SXScPUYq89ifHlVzV4YIffaUSsLXYDwmejUwVSypjt39ZNnCaPtljeehPb3IH9oFDGjyNqZJmg8edPENS8VlwBDLlUGoaZfQZOYD8A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
